# Generated by Django 4.2.7 on 2023-12-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='desc',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
