# Generated by Django 4.2.7 on 2023-12-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_subjects_review_subject_alter_review_behavior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='color',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
