# Generated by Django 4.2.7 on 2023-12-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_review_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
